Development
dpak1999/Mini-Project-ImageGenerator-Assignment pull request #1
Opened 2020-12-06 15:41 UTC by dpak1999

@sagarchoudhary96 please review

2020-12-06 17:48 UTC, sagarchoudhary96 commented on src/index.js
> +import "../node_modules/bootstrap/dist/css/bootstrap.min.css";
you can remove `../node_modules` part it can be just `bootstrap/dist/css/bootstrap.min.css`

2020-12-06 17:48 UTC, sagarchoudhary96 commented on src/App.js
> +    fetch("https://picsum.photos/500").then(
Before calling `fetch` you should  Loader to true and error value to null. so that if one time it fails on fetching and you again click button, the error is again set back to null.

2020-12-06 17:48 UTC, sagarchoudhary96 commented on src/App.js
> +        setImage(result.url);
i see you have logic to show loader as `!loading ? <Loader/> : <ImageDisplay/>` but to make it more readable. `loading ? <Loader/> : <ImageDisplay/>` i.e if loading is true then show loader else show imageDisplay component makes more sense. if you make this change then here set Loading to false instead of true.

2020-12-06 17:48 UTC, sagarchoudhary96 commented on src/App.js
> +        setLoading(true);
if you make the above change set here as well to false.

2020-12-06 17:48 UTC, sagarchoudhary96 commented on src/App.js
> +    e.preventDefault();
this is not needed and this whole function can be removed.

2020-12-06 17:48 UTC, sagarchoudhary96 commented on src/App.js
> +      <Button variant="outline-primary" className="mt-2" onClick={getImage}>
you can directly do here `onClick={fetchImage}`

2020-12-06 18:07 UTC, dpak1999 commented
yup incorporated the changes @sagarchoudhary96

2020-12-07 11:32 UTC, sagarchoudhary96 requested changes

2020-12-07 11:32 UTC, sagarchoudhary96 commented on src/App.js
> +    fetch("https://picsum.photos/500").then(
this one is still not done.

2020-12-07 11:32 UTC, sagarchoudhary96 commented on src/App.js
> +  const [loading, setLoading] = useState(true);
keep this as false only here. and make changes as per next comment

2020-12-07 11:35 UTC, sagarchoudhary96 commented on src/index.js
> +import "../node_modules/bootstrap/dist/css/bootstrap.min.css";
looks good now

2020-12-07 11:35 UTC, sagarchoudhary96 commented on src/App.js
> +        setImage(result.url);
Looks good

2020-12-07 11:35 UTC, sagarchoudhary96 commented on src/App.js
> +        setLoading(true);
looks good now

2020-12-07 11:36 UTC, sagarchoudhary96 commented
@dpak1999  make above 2 changes as well

2020-12-07 15:06 UTC, dpak1999 commented
@sagarchoudhary96 refactored please check

2020-12-07 17:49 UTC, sagarchoudhary96 approved these changes

2020-12-07 17:50 UTC, sagarchoudhary96 commented
@dpak1999 Great work 👏, You can now merge this PR.

2020-12-08 05:54 UTC, merged